# Generated by Django 5.2.9 on 2025-12-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecadesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('closing_quote', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Decades Section',
                'verbose_name_plural': 'Decades Sections',
            },
        ),
        migrations.CreateModel(
            name='DecadesTimelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_items', to='myApp.decadessection')),
            ],
            options={
                'verbose_name': 'Decades Timeline Item',
                'verbose_name_plural': 'Decades Timeline Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
