# Generated by Django 5.2.9 on 2025-12-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_decadessection_decadestimelineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='LionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="The Lion You Don't See", max_length=200)),
                ('icon', models.CharField(blank=True, default='fas fa-star', max_length=100)),
                ('intro_text', models.TextField(blank=True)),
                ('paragraph_1', models.TextField(blank=True)),
                ('paragraph_2', models.TextField(blank=True)),
                ('reflection_question', models.TextField(blank=True)),
                ('background_image_url', models.URLField(blank=True, max_length=500)),
                ('book_cover_image_url', models.URLField(blank=True, max_length=500)),
                ('closing_quote', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lion Section',
                'verbose_name_plural': 'Lion Sections',
            },
        ),
    ]
