# Generated by Django 5.2.8 on 2025-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_lionsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='cta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
