# Generated by Django 5.2.8 on 2025-12-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_contact_cta_description_contact_cta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cta_heading',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
