# Generated by Django 5.2.8 on 2025-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_contact_cta_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cta_heading',
        ),
        migrations.AddField(
            model_name='contact',
            name='cta_subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
