# Generated by Django 5.1.2 on 2025-12-12 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_contact_cta_button1_text_contact_cta_button1_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Books by Maria', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('show_publishing_service', models.BooleanField(default=True)),
                ('publishing_service_title', models.CharField(blank=True, max_length=200)),
                ('publishing_service_description', models.TextField(blank=True)),
                ('publishing_service_button_text', models.CharField(blank=True, max_length=100)),
                ('publishing_service_button_url', models.CharField(blank=True, max_length=200)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Books Section',
                'verbose_name_plural': 'Books Sections',
            },
        ),
        migrations.CreateModel(
            name='PublishedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('publication_year', models.CharField(blank=True, max_length=10)),
                ('purchase_url', models.URLField(blank=True, max_length=500)),
                ('amazon_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('books_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='myApp.bookssection')),
            ],
            options={
                'verbose_name': 'Published Book',
                'verbose_name_plural': 'Published Books',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
